<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class HeiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $heis = [
            ['uiid' => '9001', 'name' => 'Andres Bonifacio College, Inc.'],
            ['uiid' => '9002', 'name' => 'Ateneo de Zamboanga University'],
            ['uiid' => '9003', 'name' => 'Basilan State College'],
            ['uiid' => '9004', 'name' => 'Brent Hospital and Colleges Incorporated'],
            ['uiid' => '9005', 'name' => 'Claret College of Isabela'],
            ['uiid' => '9006', 'name' => 'DMC College Foundation, Inc.'],
            ['uiid' => '9008', 'name' => 'Dr. Aurelio Mendoza Memorial Colleges'],
            ['uiid' => '9009', 'name' => 'Immaculate Conception Archdiocesan School'],
            ['uiid' => '9010', 'name' => 'Juan S. Alano Memorial School, Inc.'],
            ['uiid' => '9012', 'name' => 'Jose Rizal Memorial State University - Katipunan Campus'],
            ['uiid' => '9014', 'name' => 'Marian College, Inc.'],
            ['uiid' => '9016', 'name' => 'Blancia Carreon College'],
            ['uiid' => '9017', 'name' => 'Philippine Advent College - Sindangan'],
            ['uiid' => '9018', 'name' => 'Pilar College of Zamboanga City, Inc'],
            ['uiid' => '9019', 'name' => 'Rizal Memorial Institute of Dapitan City, Inc.'],
            ['uiid' => '9020', 'name' => 'Saint Columban College, Inc.'],
            ['uiid' => '9021', 'name' => 'St. John College of Buug Foundation, Inc.'],
            ['uiid' => '9022', 'name' => 'Saint Joseph College of Sindangan Incorporated'],
            ['uiid' => '9023', 'name' => 'St. Vincent\'s College Incorporated'],
            ['uiid' => '9024', 'name' => 'Saint Estanislao Kostka College, Inc.'],
            ['uiid' => '9026', 'name' => 'Southern Mindanao Colleges Agro-Tech'],
            ['uiid' => '9027', 'name' => 'Southern City Colleges, Inc.'],
            ['uiid' => '9028', 'name' => 'Southern Mindanao Colleges'],
            ['uiid' => '9029', 'name' => 'Southern Philippine College'],
            ['uiid' => '9030', 'name' => 'Western Mindanao State University'],
            ['uiid' => '09030a', 'name' => 'Western Mindanao State University - Alicia ESU'],
            ['uiid' => '09030b', 'name' => 'Western Mindanao State University - Aurora ESU'],
            ['uiid' => '09030c', 'name' => 'Western Mindanao State University - Diplahan ESU'],
            ['uiid' => '09030d', 'name' => 'Western Mindanao State University - Imelda ESU'],
            ['uiid' => '09030e', 'name' => 'Western Mindanao State University - Ipil ESU'],
            ['uiid' => '09030f', 'name' => 'Western Mindanao State University - Mabuhay ESU'],
            ['uiid' => '09030g', 'name' => 'Western Mindanao State University - Malangas ESU'],
            ['uiid' => '09030h', 'name' => 'Western Mindanao State University - Molave ESU'],
            ['uiid' => '09030i', 'name' => 'Western Mindanao State University - Olutanga ESU'],
            ['uiid' => '09030j', 'name' => 'Western Mindanao State University - Pagadian ESU'],
            ['uiid' => '09030l', 'name' => 'Western Mindanao State University - Siay ESU'],
            ['uiid' => '09030m', 'name' => 'Western Mindanao State University - Tungawan ESU'],
            ['uiid' => '09030n', 'name' => 'Western Mindanao State University - Naga ESU'],
            ['uiid' => '09030o', 'name' => 'Western Mindanao State University - Curuan ESU'],
            ['uiid' => '9031', 'name' => 'Universidad de Zamboanga'],
            ['uiid' => '9032', 'name' => 'Zamboanga Peninsula Polytechnic State University'],
            ['uiid' => '09032a', 'name' => 'Zamboanga Peninsula Polytechnic State University - Kabasalan'],
            ['uiid' => '09032b', 'name' => 'Zamboanga Peninsula Polytechnic State University - Siay'],
            ['uiid' => '09032c', 'name' => 'Zamboanga Peninsula Polytechnic State University - Vitali'],
            ['uiid' => '9035', 'name' => 'Zamboanga State College of Marine Sciences and Technology'],
            ['uiid' => '9036', 'name' => 'J. H. Cerilles State College Main - Mati'],
            ['uiid' => '09036q', 'name' => 'J. H. Cerilles State College - Dumingag Campus'],
            ['uiid' => '9041', 'name' => 'Medina College, Incorporated'],
            ['uiid' => '9043', 'name' => 'Pagadian Capitol College, Inc.'],
            ['uiid' => '9046', 'name' => 'Aurora Pioneers Memorial College, Inc.'],
            ['uiid' => '9047', 'name' => 'Dipolog City Institute of Technology'],
            ['uiid' => '9048', 'name' => 'Jose Rizal Memorial State University'],
            ['uiid' => '9049', 'name' => 'Ebenezer Bible College and Seminary, Inc.'],
            ['uiid' => '9050', 'name' => 'St. Mary\'s College of Labason, Inc.'],
            ['uiid' => '9051', 'name' => 'J. H. Cerilles State College - Canuto M.S. Enerio Campus'],
            ['uiid' => '9053', 'name' => 'Jose Rizal Memorial State University - Dipolog Campus'],
            ['uiid' => '9054', 'name' => 'Jose Rizal Memorial State University - Siocon Campus'],
            ['uiid' => '9055', 'name' => 'AMA Computer College - Zamboanga'],
            ['uiid' => '9056', 'name' => 'Colegio de San Francisco Javier of Rizal, Zamboanga del Norte, Incorporated'],
            ['uiid' => '9058', 'name' => 'Computer Technologies Institute of Zamboanga City, Inc.'],
            ['uiid' => '9059', 'name' => 'HMIJ Foundation - Philippine Islamic College, Inc.'],
            ['uiid' => '9060', 'name' => 'Mindanao State University - Buug Campus'],
            ['uiid' => '9061', 'name' => 'Eastern Mindanao College of Technology'],
            ['uiid' => '9062', 'name' => 'Universidad de Zamboanga - Ipil'],
            ['uiid' => '9065', 'name' => 'Medina College Ipil, Inc.'],
            ['uiid' => '9068', 'name' => 'Philippine Technological and Marine Sciences'],
            ['uiid' => '9070', 'name' => 'Southern Peninsula College, Inc.'],
            ['uiid' => '9071', 'name' => 'Lucan Central Colleges, Inc.'],
            ['uiid' => '9072', 'name' => 'Sibugay Technical Institute Inc.'],
            ['uiid' => '9074', 'name' => 'Universidad de Zamboanga - Pagadian Branch Inc.'],
            ['uiid' => '9076', 'name' => 'Aim High Colleges, Inc.'],
            ['uiid' => '9077', 'name' => 'Ave Maria College'],
            ['uiid' => '9079', 'name' => 'Hyrons College Philippines, Inc.'],
            ['uiid' => '9081', 'name' => 'Jose Rizal Memorial State University - Tampilisan Campus'],
            ['uiid' => '9083', 'name' => 'Nuevo Zamboanga College, Inc.'],
            ['uiid' => '9085', 'name' => 'Philippine Advent College - Salug Campus'],
            ['uiid' => '9087', 'name' => 'Yllana Bay View College, Inc.'],
            ['uiid' => '9089', 'name' => 'Alhadeetha Mindanao College, Inc.'],
            ['uiid' => '9090', 'name' => 'Zamboanga del Sur Provincial Government College - Aurora'],
            ['uiid' => '9094', 'name' => 'Southern City Colleges - West Campus'],
            ['uiid' => '9095', 'name' => 'ZAMSULA Everlasting College'],
            ['uiid' => '9096', 'name' => 'Our Lady of Triumph Institute of Technology, Inc.'],
            ['uiid' => '9097', 'name' => 'West Prime Horizon Institute, Inc.'],
            ['uiid' => '9098', 'name' => 'Colegio de la Ciudad de Zamboanga'],
            ['uiid' => '9099', 'name' => 'Zamboanga del Sur Provincial Government College - Pagadian'],
            ['uiid' => '9100', 'name' => 'Ferndale College - Zamboanga Peninsula, Inc.'],
            ['uiid' => '9101', 'name' => 'Metro Zampen College, Inc.'],
            ['uiid' => '9102', 'name' => 'Emmaus College of Theology Foundation, Inc.'],
            ['uiid' => '9103', 'name' => 'Pagadian City International College'],
            ['uiid' => '9104', 'name' => 'Philippine Advent College - Leon B. Postigo Campus'],
            ['uiid' => '9105', 'name' => 'Zamboanga del Sur Provincial Government College - Dimataling'],
            ['uiid' => '9106', 'name' => 'Helping Hands College and Wellness Center, Inc.'],
            ['uiid' => '9108', 'name' => 'Zamboanga Peninsula Polytechnic State University - Malangas'],
            ['uiid' => '15002', 'name' => 'Central Sulu College'],
            ['uiid' => '15003', 'name' => 'Hadji Butu School of Arts and Trades'],
            ['uiid' => '15005', 'name' => 'Lapak Agricultural School'],
            ['uiid' => '15007', 'name' => 'Mindanao State University - Sulu Development Technical College'],
            ['uiid' => '15008', 'name' => 'Mindanao State University - Tawi-Tawi College of Technology and Oceonography'],
            ['uiid' => '15009', 'name' => 'Notre Dame Jolo College'],
            ['uiid' => '15013', 'name' => 'Sulu State College'],
            ['uiid' => '15014', 'name' => 'Tawi-Tawi Regional Agricultural College'],
            ['uiid' => '15025', 'name' => 'Southwestern Mindanao Islamic Institute'],
            ['uiid' => '15035', 'name' => 'Mindanao Autonomous College Foundation Inc. of Isabela City'],
            ['uiid' => '15065', 'name' => 'Sulu College of Technology, Inc.'],
            ['uiid' => 'NEW', 'name' => 'Zamboanga del Sur Provincial Government College - Margosatubig'],
            ['uiid' => 'NEW', 'name' => 'Zamboanga del Sur Provincial Government College - Molave'],
            ['uiid' => 'NEW', 'name' => 'Zamboanga del Sur Provincial Government College - Tabina'],
            ['uiid' => 'NEW', 'name' => 'Philippine Malaya College, Inc.'],
            ['uiid' => 'NEW', 'name' => 'J. H. Cerilles State College - Pagadian'],
            ['uiid' => 'NEW-Jos', 'name' => 'Zamboanga del Sur Provincial Government College - Josefina'],
            ['uiid' => 'NEW-Lap', 'name' => 'Zamboanga del Sur Provincial Government College - Lapuyan'],
            ['uiid' => 'NEW-Mah', 'name' => 'Zamboanga del Sur Provincial Government College - Mahayag'],
            ['uiid' => 'NEW-Mid', 'name' => 'Zamboanga del Sur Provincial Government College - Midsalip'],
            ['uiid' => 'NEW-Ram', 'name' => 'Zamboanga del Sur Provincial Government College - Ramon Magsaysay'],
            ['uiid' => 'NEW-Tam', 'name' => 'Zamboanga del Sur Provincial Government College - Tambulig'],
            ['uiid' => 'NEW-Tig', 'name' => 'Zamboanga del Sur Provincial Government College - Tigbao'],
            ['uiid' => 'NEW-Tuk', 'name' => 'Zamboanga del Sur Provincial Government College - Tukuran'],
            ['uiid' => 'NEW-Vin', 'name' => 'Zamboanga del Sur Provincial Government College - Vincenzo Sagun'],
        ];

        foreach ($heis as $hei) {
            DB::table('institutions')->insert([
                'uiid' => $hei['uiid'],
                'name' => $hei['name'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}