<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MunicipalitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Complete list of all 1,642 municipalities and cities grouped by province
        $municipalitiesByProvince = [
            'Abra' => [
                'Bangued', // Capital
                'Boliney',
                'Bucay',
                'Bucloc',
                'Daguioman',
                'Danglas',
                'Dolores',
                'La Paz',
                'Lacub',
                'Lagangilang',
                'Lagayan',
                'Langiden',
                'Licuan-Baay',
                'Luba',
                'Malibcong',
                'Manabo',
                'Peñarrubia',
                'Pidigan',
                'Pilar',
                'Sallapadan',
                'San Isidro',
                'San Juan',
                'San Quintin',
                'Tayum',
                'Tineg',
                'Tubo',
                'Villaviciosa', // Total: 27 municipalities
            ],
            'Agusan del Norte' => [
                'Buenavista',
                'Butuan City', // HUC, administratively independent
                'Cabadbaran City', // Capital
                'Carmen',
                'Jabonga',
                'Kitcharao',
                'Las Nieves',
                'Magallanes',
                'Nasipit',
                'Remedios T. Romualdez',
                'Santiago',
                'Tubay', // Total: 10 municipalities, 2 cities
            ],
            'Agusan del Sur' => [
                'Bayugan City',
                'Bunawan',
                'Esperanza',
                'La Paz',
                'Loreto',
                'Prosperidad', // Capital
                'Rosario',
                'San Francisco',
                'San Luis',
                'Santa Josefa',
                'Sibagat',
                'Talacogon',
                'Trento',
                'Veruela', // Total: 13 municipalities, 1 city
            ],
            'Aklan' => [
                'Altavas',
                'Balete',
                'Banga',
                'Batan',
                'Buruanga',
                'Ibajay',
                'Kalibo', // Capital
                'Lezo',
                'Libacao',
                'Madalag',
                'Makato',
                'Malay',
                'Malinao',
                'Nabas',
                'New Washington',
                'Numancia',
                'Tangalan', // Total: 17 municipalities
            ],
            'Albay' => [
                'Bacacay',
                'Camalig',
                'Daraga',
                'Guinobatan',
                'Jovellar',
                'Legazpi City', // Capital, HUC
                'Libon',
                'Ligao City',
                'Malilipot',
                'Malinao',
                'Manito',
                'Oas',
                'Pio Duran',
                'Polangui',
                'Rapu-Rapu',
                'Santo Domingo',
                'Tabaco City',
                'Tiwi', // Total: 15 municipalities, 3 cities
            ],
            'Antique' => [
                'Anini-y',
                'Barbaza',
                'Belison',
                'Bugasong',
                'Caluya',
                'Culasi',
                'Hamtic',
                'Laua-an',
                'Libertad',
                'Pandan',
                'Patnongon',
                'San Jose de Buenavista', // Capital
                'San Remigio',
                'Sebaste',
                'Sibalom',
                'Tibiao',
                'Tobias Fornier',
                'Valderrama', // Total: 18 municipalities
            ],
            'Apayao' => [
                'Calanasan',
                'Conner',
                'Flora',
                'Kabugao', // Capital
                'Luna',
                'Pudtol',
                'Santa Marcela', // Total: 7 municipalities
            ],
            'Aurora' => [
                'Baler', // Capital
                'Casiguran',
                'Dilasag',
                'Dinalungan',
                'Dingalan',
                'Dipaculao',
                'Maria Aurora',
                'San Luis', // Total: 8 municipalities
            ],
            'Basilan' => [
                'Akbar',
                'Al-Barka',
                'Hadji Mohammad Ajul',
                'Hadji Muhtamad',
                'Isabela City', // ICC
                'Lamitan City', // Capital
                'Lantawan',
                'Maluso',
                'Sumisip',
                'Tabuan-Lasa',
                'Tipo-Tipo',
                'Tuburan',
                'Ungkaya Pukan', // Total: 11 municipalities, 2 cities
            ],
            'Bataan' => [
                'Abucay',
                'Bagac',
                'Balanga City', // Capital
                'Dinalupihan',
                'Hermosa',
                'Limay',
                'Mariveles',
                'Morong',
                'Orani',
                'Orion',
                'Pilar',
                'Samal', // Total: 11 municipalities, 1 city
            ],
            'Batanes' => [
                'Basco', // Capital
                'Itbayat',
                'Ivana',
                'Mahatao',
                'Sabtang',
                'Uyugan', // Total: 6 municipalities
            ],
            'Batangas' => [
                'Agoncillo',
                'Alitagtag',
                'Balayan',
                'Balete',
                'Batangas City', // Capital
                'Bauan',
                'Calaca',
                'Calatagan',
                'Cuenca',
                'Ibaan',
                'Laurel',
                'Lemery',
                'Lian',
                'Lipa City', // HUC
                'Lobo',
                'Mabini',
                'Malvar',
                'Mataasnakahoy',
                'Nasugbu',
                'Padre Garcia',
                'Rosario',
                'San Jose',
                'San Juan',
                'San Luis',
                'San Nicolas',
                'San Pascual',
                'Santa Teresita',
                'Santo Tomas City',
                'Taal',
                'Talisay',
                'Tanauan City',
                'Taysan',
                'Tingloy',
                'Tuy', // Total: 29 municipalities, 5 cities
            ],
            'Benguet' => [
                'Atok',
                'Baguio City', // HUC
                'Bakun',
                'Bokod',
                'Buguias',
                'Itogon',
                'Kabayan',
                'Kapangan',
                'Kibungan',
                'La Trinidad', // Capital
                'Mankayan',
                'Sablan',
                'Tuba',
                'Tublay', // Total: 13 municipalities, 1 city
            ],
            'Biliran' => [
                'Almeria',
                'Biliran',
                'Cabucgayan',
                'Caibiran',
                'Culaba',
                'Kawayan',
                'Maripipi',
                'Naval', // Capital
            ],
            'Bohol' => [
                'Alburquerque',
                'Alicia',
                'Anda',
                'Antequera',
                'Baclayon',
                'Balilihan',
                'Batuan',
                'Bien Unido',
                'Bilar',
                'Buenavista',
                'Calape',
                'Candijay',
                'Carmen',
                'Catigbian',
                'Clarin',
                'Corella',
                'Cortes',
                'Dagohoy',
                'Danao',
                'Dauis',
                'Dimiao',
                'Duero',
                'Garcia Hernandez',
                'Getafe',
                'Guindulman',
                'Inabanga',
                'Jetafe',
                'Lila',
                'Loay',
                'Loboc',
                'Loon',
                'Mabini',
                'Maribojoc',
                'Panglao',
                'Pilar',
                'President Carlos P. Garcia',
                'Sagbayan',
                'San Isidro',
                'San Miguel',
                'Sevilla',
                'Sierra Bullones',
                'Sikatuna',
                'Tagbilaran City', // Capital
                'Talibon',
                'Trinidad',
                'Tubigon',
                'Ubay',
                'Valencia', // Total: 47 municipalities, 1 city
            ],
            'Bukidnon' => [
                'Baungon',
                'Cabanglasan',
                'Damulog',
                'Dangcagan',
                'Don Carlos',
                'Impasugong',
                'Kadingilan',
                'Kalilangan',
                'Kibawe',
                'Kitaotao',
                'Lantapan',
                'Libona',
                'Malaybalay City', // Capital
                'Malitbog',
                'Manolo Fortich',
                'Maramag',
                'Pangantucan',
                'Quezon',
                'San Fernando',
                'Sumilao',
                'Talakag',
                'Valencia City', // Total: 20 municipalities, 2 cities
            ],
            'Bulacan' => [
                'Angat',
                'Balagtas',
                'Baliuag',
                'Bocaue',
                'Bulakan',
                'Bustos',
                'Calumpit',
                'Doña Remedios Trinidad',
                'Guiguinto',
                'Hagonoy',
                'Malolos City', // Capital
                'Marilao',
                'Meycauayan City',
                'Norzagaray',
                'Obando',
                'Pandi',
                'Paombong',
                'Plaridel',
                'Pulilan',
                'San Jose del Monte City',
                'San Miguel',
                'San Rafael',
                'Santa Maria', // Total: 21 municipalities, 3 cities
            ],
            'Cagayan' => [
                'Abulug',
                'Alcala',
                'Allacapan',
                'Amulung',
                'Aparri',
                'Baggao',
                'Ballesteros',
                'Buguey',
                'Calayan',
                'Camalaniugan',
                'Claveria',
                'Enrile',
                'Gattaran',
                'Gonzaga',
                'Iguig',
                'Lal-lo',
                'Lasam',
                'Pamplona',
                'Peñablanca',
                'Piat',
                'Rizal',
                'Sanchez-Mira',
                'Santa Ana',
                'Santa Praxedes',
                'Santa Teresita',
                'Santo Niño',
                'Solana',
                'Tuao',
                'Tuguegarao City', // Capital
            ],
            'Camarines Norte' => [
                'Basud',
                'Capalonga',
                'Daet', // Capital
                'Jose Panganiban',
                'Labo',
                'Mercedes',
                'Paracale',
                'San Lorenzo Ruiz',
                'San Vicente',
                'Santa Elena',
                'Talisay',
                'Vinzons', // Total: 12 municipalities
            ],
            'Camarines Sur' => [
                'Baao',
                'Balatan',
                'Bato',
                'Bombon',
                'Buhi',
                'Bula',
                'Cabusao',
                'Calabanga',
                'Camaligan',
                'Canaman',
                'Caramoan',
                'Del Gallego',
                'Gainza',
                'Garchitorena',
                'Goa',
                'Iriga City',
                'Lagonoy',
                'Libmanan',
                'Lupi',
                'Magarao',
                'Milaor',
                'Minalabac',
                'Nabua',
                'Naga City', // ICC
                'Ocampo',
                'Pamplona',
                'Pasacao',
                'Pili', // Capital
                'Presentacion',
                'Ragay',
                'Sagñay',
                'San Fernando',
                'San Jose',
                'Sipocot',
                'Siruma',
                'Tigaon',
                'Tinambac', // Total: 35 municipalities, 2 cities
            ],
            'Camiguin' => [
                'Catarman',
                'Guinsiliban',
                'Mahinog',
                'Mambajao', // Capital
                'Sagay', // Total: 5 municipalities
            ],
            'Capiz' => [
                'Cuartero',
                'Dao',
                'Dumalag',
                'Dumarao',
                'Ivisan',
                'Jamindan',
                'Maayon',
                'Mambusao',
                'Panay',
                'Panitan',
                'Pilar',
                'Pontevedra',
                'President Roxas',
                'Roxas City', // Capital
                'Sapian',
                'Sigma',
                'Tapaz', // Total: 16 municipalities, 1 city
            ],
            'Catanduanes' => [
                'Bagamanoc',
                'Baras',
                'Bato',
                'Caramoran',
                'Gigmoto',
                'Pandan',
                'Panganiban',
                'San Andres',
                'San Miguel',
                'Viga',
                'Virac', // Capital
            ],
            'Cavite' => [
                'Alfonso',
                'Amadeo',
                'Bacoor City',
                'Carmona',
                'Cavite City',
                'Dasmariñas City', // HUC
                'General Emilio Aguinaldo',
                'General Mariano Alvarez',
                'General Trias City',
                'Imus City', // Capital
                'Indang',
                'Kawit',
                'Magallanes',
                'Maragondon',
                'Mendez',
                'Naic',
                'Noveleta',
                'Rosario',
                'Silang',
                'Tagaytay City',
                'Tanza',
                'Ternate',
                'Trece Martires City', // Total: 16 municipalities, 7 cities
            ],
            'Cebu' => [
                'Alcantara',
                'Alcoy',
                'Alegria',
                'Aloguinsan',
                'Argao',
                'Asturias',
                'Badian',
                'Balamban',
                'Bantayan',
                'Barili',
                'Bogo City',
                'Boljoon',
                'Borbon',
                'Carcar City',
                'Carmen',
                'Catmon',
                'Cebu City', // HUC
                'Compostela',
                'Consolacion',
                'Cordova',
                'Daanbantayan',
                'Dalaguete',
                'Danao City',
                'Dumanjug',
                'Ginatilan',
                'Lapu-Lapu City', // HUC
                'Liloan',
                'Madridejos',
                'Malabuyoc',
                'Mandaue City', // HUC
                'Medellin',
                'Minglanilla',
                'Moalboal',
                'Naga City',
                'Oslob',
                'Pilar',
                'Pinamungajan',
                'Poro',
                'Ronda',
                'Samboan',
                'San Fernando',
                'San Francisco',
                'San Remigio',
                'Santa Fe',
                'Santander',
                'Sibonga',
                'Sogod',
                'Tabogon',
                'Tabuelan',
                'Talisay City',
                'Toledo City',
                'Tuburan',
                'Tudela', // Total: 44 municipalities, 9 cities
            ],
            'Cotabato' => [
                'Alamada',
                'Aleosan',
                'Antipas',
                'Arakan',
                'Banisilan',
                'Carmen',
                'Kabacan',
                'Kidapawan City', // Capital
                'Libungan',
                'M’lang',
                'Magpet',
                'Makilala',
                'Matalam',
                'Midsayap',
                'Pigcawayan',
                'Pikit',
                'President Roxas',
                'Tulunan', // Total: 17 municipalities, 1 city
            ],
            'Davao de Oro' => [
                'Compostela',
                'Laak',
                'Mabini',
                'Maco',
                'Maragusan',
                'Mawab',
                'Monkayo',
                'Montevista',
                'Nabunturan', // Capital
                'New Bataan',
                'Pantukan', // Total: 11 municipalities
            ],
            'Davao del Norte' => [
                'Asuncion',
                'Braulio E. Dujali',
                'Carmen',
                'Kapalong',
                'New Corella',
                'Panabo City',
                'Samal City',
                'San Isidro',
                'Santo Tomas',
                'Tagum City', // Capital
                'Talaingod', // Total: 8 municipalities, 3 cities
            ],
            'Davao del Sur' => [
                'Bansalan',
                'Davao City', // HUC
                'Digos City', // Capital
                'Hagonoy',
                'Kiblawan',
                'Magsaysay',
                'Malalag',
                'Matanao',
                'Padada',
                'Santa Cruz',
                'Sulop', // Total: 9 municipalities, 2 cities
            ],
            'Davao Occidental' => [
                'Don Marcelino',
                'Jose Abad Santos',
                'Malita', // Capital
                'Santa Maria',
                'Sarangani', // Total: 5 municipalities
            ],
            'Davao Oriental' => [
                'Baganga',
                'Banaybanay',
                'Boston',
                'Caraga',
                'Cateel',
                'Governor Generoso',
                'Lupon',
                'Manay',
                'Mati City', // Capital
                'San Isidro',
                'Tarragona', // Total: 10 municipalities, 1 city
            ],
            'Dinagat Islands' => [
                'Basilisa',
                'Cagdianao',
                'Dinagat',
                'Libjo',
                'Loreto',
                'San Jose', // Capital
                'Tubajon', // Total: 7 municipalities
            ],
            'Eastern Samar' => [
                'Arteche',
                'Balangiga',
                'Balangkayan',
                'Borongan City', // Capital
                'Can-avid',
                'Dolores',
                'General MacArthur',
                'Giporlos',
                'Guiuan',
                'Hernani',
                'Jipapad',
                'Lawaan',
                'Llorente',
                'Maslog',
                'Maydolong',
                'Mercedes',
                'Oras',
                'Quinapondan',
                'Salcedo',
                'San Julian',
                'San Policarpo',
                'Sulat',
                'Taft', // Total: 22 municipalities, 1 city
            ],
            'Guimaras' => [
                'Buenavista',
                'Jordan', // Capital
                'Nueva Valencia',
                'San Lorenzo',
                'Sibunag', // Total: 5 municipalities
            ],
            'Ifugao' => [
                'Aguinaldo',
                'Alfonso Lista',
                'Asipulo',
                'Banaue',
                'Hingyon',
                'Hungduan',
                'Kiangan',
                'Lagawe', // Capital
                'Lamut',
                'Mayoyao',
                'Tinoc', // Total: 11 municipalities
            ],
            'Ilocos Norte' => [
                'Adams',
                'Bacarra',
                'Badoc',
                'Bangui',
                'Banna',
                'Batac City',
                'Burgos',
                'Carasi',
                'Currimao',
                'Dingras',
                'Dumalneg',
                'Laoag City', // Capital
                'Marcos',
                'Nueva Era',
                'Pagudpud',
                'Paoay',
                'Pasuquin',
                'Piddig',
                'Pinili',
                'San Nicolas',
                'Sarrat',
                'Solsona',
                'Vintar', // Total: 21 municipalities, 2 cities
            ],
            'Ilocos Sur' => [
                'Alilem',
                'Banayoyo',
                'Bantay',
                'Burgos',
                'Cabugao',
                'Candon City',
                'Caoayan',
                'Cervantes',
                'Galimuyod',
                'Gregorio del Pilar',
                'Lidlidda',
                'Magsingal',
                'Nagbukel',
                'Narvacan',
                'Quirino',
                'Salcedo',
                'San Emilio',
                'San Esteban',
                'San Ildefonso',
                'San Juan',
                'San Vicente',
                'Santa',
                'Santa Catalina',
                'Santa Cruz',
                'Santa Lucia',
                'Santa Maria',
                'Santiago',
                'Santo Domingo',
                'Sigay',
                'Sinait',
                'Sugpon',
                'Suyo',
                'Tagudin',
                'Vigan City', // Capital
            ],
            'Iloilo' => [
                'Ajuy',
                'Alimodian',
                'Anilao',
                'Badiangan',
                'Balasan',
                'Banate',
                'Barotac Nuevo',
                'Barotac Viejo',
                'Batad',
                'Bingawan',
                'Cabatuan',
                'Calinog',
                'Carles',
                'Concepcion',
                'Dingle',
                'Dueñas',
                'Dumangas',
                'Estancia',
                'Guimbal',
                'Igbaras',
                'Iloilo City', // HUC
                'Janiuay',
                'Lambunao',
                'Leganes',
                'Lemery',
                'Leon',
                'Maasin',
                'Miagao',
                'Mina',
                'New Lucena',
                'Oton',
                'Passi City',
                'Pavia',
                'Pototan',
                'San Dionisio',
                'San Enrique',
                'San Joaquin',
                'San Miguel',
                'San Rafael',
                'Santa Barbara',
                'Sara',
                'Tigbauan',
                'Tubungan',
                'Zarraga', // Total: 42 municipalities, 2 cities
            ],
            'Isabela' => [
                'Alicia',
                'Angadanan',
                'Aurora',
                'Benito Soliven',
                'Burgos',
                'Cabagan',
                'Cabatuan',
                'Cauayan City',
                'Cordon',
                'Delfin Albano',
                'Dinapigue',
                'Divilacan',
                'Echague',
                'Gamu',
                'Ilagan City', // Capital
                'Jones',
                'Luna',
                'Maconacon',
                'Mallig',
                'Naguilian',
                'Palanan',
                'Quezon',
                'Quirino',
                'Ramon',
                'Reina Mercedes',
                'Roxas',
                'San Agustin',
                'San Guillermo',
                'San Isidro',
                'San Manuel',
                'San Mariano',
                'San Mateo',
                'San Pablo',
                'Santa Maria',
                'Santiago City', // ICC
                'Santo Tomas',
                'Tumauini', // Total: 34 municipalities, 3 cities
            ],
            'Kalinga' => [
                'Balbalan',
                'Lubuagan',
                'Pasil',
                'Pinukpuk',
                'Rizal',
                'Tabuk City', // Capital
                'Tanudan',
                'Tinglayan', // Total: 7 municipalities, 1 city
            ],
            'La Union' => [
                'Agoo',
                'Aringay',
                'Bacnotan',
                'Bagulin',
                'Balaoan',
                'Bangar',
                'Bauang',
                'Burgos',
                'Caba',
                'Luna',
                'Naguilian',
                'Pugo',
                'Rosario',
                'San Fernando City', // Capital
                'San Gabriel',
                'San Juan',
                'Santo Tomas',
                'Santol',
                'Sudipen',
                'Tubao', // Total: 19 municipalities, 1 city
            ],
            'Laguna' => [
                'Alaminos',
                'Bay',
                'Biñan City',
                'Cabuyao City',
                'Calamba City',
                'Calauan',
                'Cavinti',
                'Famy',
                'Kalayaan',
                'Liliw',
                'Los Baños',
                'Luisiana',
                'Lumban',
                'Mabitac',
                'Magdalena',
                'Majayjay',
                'Nagcarlan',
                'Paete',
                'Pagsanjan',
                'Pakil',
                'Pangil',
                'Pila',
                'Rizal',
                'San Pablo City',
                'San Pedro City',
                'Santa Cruz', // Capital
                'Santa Maria',
                'Santa Rosa City',
                'Siniloan',
                'Victoria', // Total: 24 municipalities, 6 cities
            ],
            'Lanao del Norte' => [
                'Bacolod',
                'Baloi',
                'Baroy',
                'Iligan City', // HUC
                'Kapatagan',
                'Kauswagan',
                'Kolambugan',
                'Lala',
                'Linamon',
                'Magsaysay',
                'Maigo',
                'Matungao',
                'Munai',
                'Nunungan',
                'Pantao Ragat',
                'Pantar',
                'Poona Piagapo',
                'Salvador',
                'Sapad',
                'Sultan Naga Dimaporo',
                'Tagoloan',
                'Tangcal',
                'Tubod', // Capital
            ],
            'Lanao del Sur' => [
                'Amai Manabilang',
                'Bacayawan',
                'Balabagan',
                'Balindong',
                'Bayang',
                'Binidayan',
                'Buadiposo-Buntong',
                'Bubong',
                'Butig',
                'Calanogas',
                'Ditsaan-Ramain',
                'Ganassi',
                'Kapai',
                'Kapatagan',
                'Lumba-Bayabao',
                'Lumbaca-Unayan',
                'Lumbatan',
                'Lumbayanague',
                'Madalum',
                'Madamba',
                'Maguing',
                'Malabang',
                'Marantao',
                'Marawi City', // Capital
                'Marogong',
                'Masiu',
                'Mulondo',
                'Pagayawan',
                'Piagapo',
                'Picong',
                'Poona Bayabao',
                'Pualas',
                'Saguiaran',
                'Sultan Dumalondong',
                'Tagoloan II',
                'Tamparan',
                'Taraka',
                'Tubaran',
                'Tugaya',
                'Wao', // Total: 39 municipalities, 1 city
            ],
            'Leyte' => [
                'Abuyog',
                'Alangalang',
                'Albuera',
                'Babatngon',
                'Barugo',
                'Bato',
                'Baybay City',
                'Burauen',
                'Calubian',
                'Capoocan',
                'Carigara',
                'Dagami',
                'Dulag',
                'Hilongos',
                'Hindang',
                'Inopacan',
                'Isabel',
                'Jaro',
                'Javier',
                'Julita',
                'Kananga',
                'La Paz',
                'Leyte',
                'MacArthur',
                'Mahaplag',
                'Matag-ob',
                'Matalom',
                'Mayorga',
                'Merida',
                'Ormoc City', // ICC
                'Palo',
                'Palompon',
                'Pastrana',
                'San Isidro',
                'San Miguel',
                'Santa Fe',
                'Tabontabon',
                'Tabon-tabon',
                'Tacloban City', // HUC
                'Tanauan',
                'Tolosa',
                'Tunga',
                'Villaba', // Total: 40 municipalities, 3 cities
            ],
            'Maguindanao del Norte' => [
                'Barira',
                'Buldon',
                'Datu Blah T. Sinsuat',
                'Datu Odin Sinsuat', // Capital
                'Kabuntalan',
                'Matanog',
                'Northern Kabuntalan',
                'Parang',
                'Sultan Kudarat',
                'Sultan Mastura',
                'Talitay',
                'Upi', // Total: 12 municipalities
            ],
            'Maguindanao del Sur' => [
                'Ampatuan',
                'Buluan', // Capital
                'Datu Abdullah Sangki',
                'Datu Anggal Midtimbang',
                'Datu Hoffer Ampatuan',
                'Datu Montawal',
                'Datu Paglas',
                'Datu Piang',
                'Datu Salibo',
                'Datu Saudi-Ampatuan',
                'Datu Unsay',
                'Gen. S. K. Pendatun',
                'Guindulungan',
                'Mamasapano',
                'Mangudadatu',
                'Pagalungan',
                'Paglat',
                'Pandag',
                'Rajah Buayan',
                'Shariff Aguak',
                'Shariff Saydona Mustapha',
                'South Upi',
                'Sultan sa Barongis',
                'Talayan', // Total: 24 municipalities
            ],
            'Marinduque' => [
                'Boac', // Capital
                'Buenavista',
                'Gasan',
                'Mogpog',
                'Santa Cruz',
                'Torrijos', // Total: 6 municipalities
            ],
            'Masbate' => [
                'Aroroy',
                'Baleno',
                'Balud',
                'Batuan',
                'Cataingan',
                'Cawayan',
                'Claveria',
                'Dimasalang',
                'Esperanza',
                'Mandaon',
                'Masbate City', // Capital
                'Milagros',
                'Mobo',
                'Monreal',
                'Palanas',
                'Pio V. Corpuz',
                'Placer',
                'San Fernando',
                'San Jacinto',
                'San Pascual',
                'Uson', // Total: 20 municipalities, 1 city
            ],
            'Misamis Occidental' => [
                'Aloran',
                'Baliangao',
                'Bonifacio',
                'Calamba',
                'Clarin',
                'Concepcion',
                'Don Victoriano Chiongbian',
                'Jimenez',
                'Lopez Jaena',
                'Oroquieta City', // Capital
                'Ozamiz City',
                'Panaon',
                'Plaridel',
                'Sapang Dalaga',
                'Sinacaban',
                'Tangub City',
                'Tudela', // Total: 14 municipalities, 3 cities
            ],
            'Misamis Oriental' => [
                'Alubijid',
                'Balingasag',
                'Balingoan',
                'Binuangan',
                'Cagayan de Oro City', // HUC
                'Claveria',
                'El Salvador City',
                'Gingoog City',
                'Gitagum',
                'Initao',
                'Jasaan',
                'Kinoguitan',
                'Lagonglong',
                'Laguindingan',
                'Libertad',
                'Lugait',
                'Magsaysay',
                'Manticao',
                'Medina',
                'Naawan',
                'Opol',
                'Salay',
                'Sugbongcogon',
                'Tagoloan',
                'Talisayan',
                'Villanueva', // Total: 23 municipalities, 3 cities
            ],
            'Mountain Province' => [
                'Barlig',
                'Bauko',
                'Besao',
                'Bontoc', // Capital
                'Natonin',
                'Paracelis',
                'Sabangan',
                'Sadanga',
                'Sagada',
                'Tadian', // Total: 10 municipalities
            ],
            'Negros Occidental' => [
                'Bacolod City', // HUC
                'Bago City',
                'Binalbagan',
                'Cadiz City',
                'Calatrava',
                'Candoni',
                'Cauayan',
                'Enrique B. Magalona',
                'Escalante City',
                'Himamaylan City',
                'Hinigaran',
                'Hinoba-an',
                'Ilog',
                'Isabela',
                'Kabankalan City',
                'La Carlota City',
                'La Castellana',
                'Manapla',
                'Moises Padilla',
                'Murcia',
                'Pontevedra',
                'Pulupandan',
                'Sagay City',
                'Salvador Benedicto',
                'San Carlos City',
                'San Enrique',
                'Silay City',
                'Sipalay City',
                'Talisay City',
                'Toboso',
                'Valladolid',
                'Victorias City', // Total: 19 municipalities, 13 cities
            ],
            'Negros Oriental' => [
                'Amlan',
                'Ayungon',
                'Bacong',
                'Bais City',
                'Basay',
                'Bayawan City',
                'Bindoy',
                'Canlaon City',
                'Dauin',
                'Dumaguete City', // Capital
                'Guihulngan City',
                'Jimalalud',
                'La Libertad',
                'Mabinay',
                'Manjuyod',
                'Pamplona',
                'San Jose',
                'Santa Catalina',
                'Siaton',
                'Sibulan',
                'Tanjay City',
                'Tayasan',
                'Valencia',
                'Vallehermoso',
                'Zamboanguita', // Total: 19 municipalities, 6 cities
            ],
            'Northern Samar' => [
                'Allen',
                'Biri',
                'Bobon',
                'Capul',
                'Catarman', // Capital
                'Catubig',
                'Gamay',
                'Laoang',
                'Lapinig',
                'Las Navas',
                'Lavezares',
                'Lope de Vega',
                'Mapanas',
                'Mondragon',
                'Palapag',
                'Pambujan',
                'Rosario',
                'San Antonio',
                'San Isidro',
                'San Jose',
                'San Roque',
                'San Vicente',
                'Silvino Lobos',
                'Victoria', // Total: 24 municipalities
            ],
            'Nueva Ecija' => [
                'Aliaga',
                'Bongabon',
                'Cabanatuan City', // HUC
                'Cabiao',
                'Carranglan',
                'Cuyapo',
                'Gabaldon',
                'Gapan City',
                'General Mamerto Natividad',
                'General Tinio',
                'Guimba',
                'Jaen',
                'Laur',
                'Licab',
                'Llanera',
                'Lupao',
                'Muñoz City',
                'Nampicuan',
                'Palayan City', // Capital
                'Pantabangan',
                'Peñaranda',
                'Quezon',
                'Rizal',
                'San Antonio',
                'San Isidro',
                'San Jose City',
                'San Leonardo',
                'Santa Rosa',
                'Santo Domingo',
                'Talavera',
                'Talugtug',
                'Zaragoza', // Total: 27 municipalities, 5 cities
            ],
            'Nueva Vizcaya' => [
                'Alfonso Castañeda',
                'Ambaguio',
                'Aritao',
                'Bagabag',
                'Bambang',
                'Bayombong', // Capital
                'Diadi',
                'Dupax del Norte',
                'Dupax del Sur',
                'Kasibu',
                'Kayapa',
                'Quezon',
                'Santa Fe',
                'Solano',
                'Villaverde', // Total: 15 municipalities
            ],
            'Occidental Mindoro' => [
                'Abra de Ilog',
                'Calintaan',
                'Looc',
                'Lubang',
                'Magsaysay',
                'Mamburao',
                'Paluan',
                'Rizal',
                'Sablayan',
                'San Jose', // Capital
                'Santa Cruz', // Total: 11 municipalities
            ],
            'Oriental Mindoro' => [
                'Baco',
                'Bansud',
                'Bongabong',
                'Bulalacao',
                'Calapan City', // Capital
                'Gloria',
                'Mansalay',
                'Naujan',
                'Pinamalayan',
                'Pola',
                'Puerto Galera',
                'Roxas',
                'San Teodoro',
                'Socorro',
                'Victoria', // Total: 14 municipalities, 1 city
            ],
            'Palawan' => [
                'Aborlan',
                'Agutaya',
                'Araceli',
                'Balabac',
                'Bataraza',
                'Brooke’s Point',
                'Busuanga',
                'Cagayancillo',
                'Coron',
                'Culion',
                'Dumaran',
                'El Nido',
                'Kalayaan',
                'Linapacan',
                'Magsaysay',
                'Narra',
                'Puerto Princesa City', // HUC
                'Quezon',
                'Rizal',
                'Roxas',
                'San Vicente',
                'Sofronio Española',
                'Taytay', // Total: 23 municipalities, 1 city
            ],
            'Pampanga' => [
                'Angeles City', // HUC
                'Apalit',
                'Arayat',
                'Bacolor',
                'Candaba',
                'Floridablanca',
                'Guagua',
                'Lubao',
                'Mabalacat City',
                'Macabebe',
                'Magalang',
                'Masantol',
                'Mexico',
                'Minalin',
                'Porac',
                'San Fernando City', // Capital
                'San Luis',
                'San Simon',
                'Santa Ana',
                'Santa Rita',
                'Santo Tomas',
                'Sasmuan', // Total: 19 municipalities, 3 cities
            ],
            'Pangasinan' => [
                'Agno',
                'Aguilar',
                'Alaminos City',
                'Alcala',
                'Anda',
                'Asingan',
                'Balungao',
                'Bani',
                'Basista',
                'Bautista',
                'Bayambang',
                'Binalonan',
                'Binmaley',
                'Bolinao',
                'Bugallon',
                'Burgos',
                'Calasiao',
                'Dagupan City', // HUC
                'Dasol',
                'Infanta',
                'Labrador',
                'Laoac',
                'Lingayen', // Capital
                'Mabini',
                'Malasiqui',
                'Manaoag',
                'Mangaldan',
                'Mangatarem',
                'Mapandan',
                'Natividad',
                'Pozorrubio',
                'Rosales',
                'San Carlos City',
                'San Fabian',
                'San Jacinto',
                'San Manuel',
                'San Nicolas',
                'San Quintin',
                'Santa Barbara',
                'Santa Maria',
                'Santo Tomas',
                'Sison',
                'Sual',
                'Tayug',
                'Umingan',
                'Urdaneta City',
                'Villasis', // Total: 44 municipalities, 4 cities
            ],
            'Quezon' => [
                'Agdangan',
                'Alabat',
                'Atimonan',
                'Buenavista',
                'Burdeos',
                'Calauag',
                'Candelaria',
                'Catanauan',
                'Dolores',
                'General Luna',
                'General Nakar',
                'Guinayangan',
                'Gumaca',
                'Infanta',
                'Jomalig',
                'Lopez',
                'Lucban',
                'Lucena City', // HUC
                'Macalelon',
                'Mauban',
                'Mulanay',
                'Padre Burgos',
                'Pagbilao',
                'Panukulan',
                'Patnanungan',
                'Perez',
                'Pitogo',
                'Plaridel',
                'Polillo',
                'Quezon',
                'Real',
                'Sampaloc',
                'San Andres',
                'San Antonio',
                'San Francisco',
                'San Narciso',
                'Sariaya',
                'Tagkawayan',
                'Tayabas City',
                'Tiaong',
                'Unisan', // Total: 39 municipalities, 2 cities
            ],
            'Quirino' => [
                'Aglipay',
                'Cabarroguis', // Capital
                'Diffun',
                'Maddela',
                'Nagtipunan',
                'Saguday', // Total: 6 municipalities
            ],
            'Rizal' => [
                'Angono',
                'Antipolo City', // Capital
                'Baras',
                'Binangonan',
                'Cainta',
                'Cardona',
                'Jalajala',
                'Morong',
                'Pililla',
                'Rodriguez',
                'San Mateo',
                'Tanay',
                'Taytay',
                'Teresa', // Total: 13 municipalities, 1 city
            ],
            'Romblon' => [
                'Alcantara',
                'Banton',
                'Cajidiocan',
                'Calatrava',
                'Concepcion',
                'Corcuera',
                'Ferrol',
                'Looc',
                'Magdiwang',
                'Odiongan',
                'Romblon', // Capital
                'San Agustin',
                'San Andres',
                'San Fernando',
                'San Jose',
                'Santa Fe',
                'Santa Maria', // Total: 17 municipalities
            ],
            'Samar' => [
                'Almagro',
                'Basey',
                'Calbayog City',
                'Calbiga',
                'Catbalogan City', // Capital
                'Daram',
                'Gandara',
                'Hinabangan',
                'Jiabong',
                'Marabut',
                'Matuguinao',
                'Motiong',
                'Pagsanghan',
                'Paranas',
                'Pinabacdao',
                'San Jorge',
                'San Jose de Buan',
                'San Sebastian',
                'Santa Margarita',
                'Santa Rita',
                'Santo Niño',
                'Tagapul-an',
                'Talalora',
                'Tarangnan',
                'Villareal',
                'Zumarraga', // Total: 24 municipalities, 2 cities
            ],
            'Sarangani' => [
                'Alabel', // Capital
                'Glan',
                'Kiamba',
                'Maasim',
                'Maitum',
                'Malapatan',
                'Malungon', // Total: 7 municipalities
            ],
            'Siquijor' => [
                'Enrique Villanueva',
                'Larena',
                'Lazi',
                'Maria',
                'San Juan',
                'Siquijor', // Capital
            ],
            'Sorsogon' => [
                'Barcelona',
                'Bulan',
                'Bulusan',
                'Casiguran',
                'Castilla',
                'Donsol',
                'Gubat',
                'Irosin',
                'Juban',
                'Magdalena',
                'Matnog',
                'Pilar',
                'Prieto Diaz',
                'Santa Magdalena',
                'Sorsogon City', // Capital
            ],
            'South Cotabato' => [
                'Banga',
                'General Santos City', // HUC
                'Koronadal City', // Capital
                'Lake Sebu',
                'Norala',
                'Polomolok',
                'Santo Niño',
                'Surallah',
                'T’boli',
                'Tampakan',
                'Tantangan',
                'Tupi', // Total: 10 municipalities, 2 cities
            ],
            'Southern Leyte' => [
                'Anahawan',
                'Bontoc',
                'Hinunangan',
                'Hinundayan',
                'Libagon',
                'Liloan',
                'Limasawa',
                'Maasin City', // Capital
                'Macrohon',
                'Malitbog',
                'Padre Burgos',
                'Pintuyan',
                'Saint Bernard',
                'San Francisco',
                'San Juan',
                'San Ricardo',
                'Silago',
                'Sogod',
                'Tomas Oppus', // Total: 18 municipalities, 1 city
            ],
            'Sultan Kudarat' => [
                'Bagumbayan',
                'Columbio',
                'Esperanza',
                'Isulan',
                'Kalamansig',
                'Lambayong',
                'Lebak',
                'Lutayan',
                'Palimbang',
                'President Quirino',
                'Senator Ninoy Aquino',
                'Tacurong City', // Capital
            ],
            'Sulu' => [
                'Banguingui',
                'Hadji Panglima Tahil',
                'Indanan',
                'Jolo', // Capital
                'Kalingalan Caluang',
                'Lugus',
                'Luuk',
                'Maimbung',
                'Old Panamao',
                'Omar',
                'Pandami',
                'Pangutaran',
                'Parang',
                'Pata',
                'Patikul',
                'Siasi',
                'Talipao',
                'Tapul',
                'Tongkil', // Total: 19 municipalities
            ],
            'Surigao del Norte' => [
                'Alegria',
                'Bacuag',
                'Burgos',
                'Claver',
                'Dapa',
                'Del Carmen',
                'General Luna',
                'Gigaquit',
                'Mainit',
                'Malimono',
                'Pilar',
                'Placer',
                'San Benito',
                'San Francisco',
                'San Isidro',
                'San Jose',
                'Santa Monica',
                'Sison',
                'Socorro',
                'Surigao City', // Capital
                'Tagana-an',
                'Tubod', // Total: 20 municipalities, 1 city
            ],
            'Surigao del Sur' => [
                'Barobo',
                'Bayabas',
                'Bislig City',
                'Cagwait',
                'Cantilan',
                'Carmen',
                'Carrascal',
                'Cortes',
                'Hinatuan',
                'Lanuza',
                'Lianga',
                'Lingig',
                'Madrid',
                'Marihatag',
                'San Agustin',
                'San Miguel',
                'Tagbina',
                'Tago',
                'Tandag City', // Capital
            ],
            'Tarlac' => [
                'Anao',
                'Bamban',
                'Camiling',
                'Capas',
                'Concepcion',
                'Gerona',
                'La Paz',
                'Mayantoc',
                'Moncada',
                'Paniqui',
                'Pura',
                'Ramos',
                'San Clemente',
                'San Jose',
                'San Manuel',
                'Santa Ignacia',
                'Tarlac City', // Capital
                'Victoria', // Total: 17 municipalities, 1 city
            ],
            'Tawi-Tawi' => [
                'Bongao', // Capital
                'Languyan',
                'Mapun',
                'Panglima Sugala',
                'Sapa-Sapa',
                'Sibutu',
                'Simunul',
                'Sitangkai',
                'South Ubian',
                'Tandubas',
                'Turtle Islands', // Total: 11 municipalities
            ],
            'Zambales' => [
                'Botolan',
                'Cabangan',
                'Candelaria',
                'Castillejos',
                'Iba', // Capital
                'Masinloc',
                'Olongapo City', // HUC
                'Palauig',
                'San Antonio',
                'San Felipe',
                'San Marcelino',
                'San Narciso',
                'Santa Cruz',
                'Subic', // Total: 13 municipalities, 1 city
            ],
            'Zamboanga del Norte' => [
                'Bacungan',
                'Baliguian',
                'Dapitan City',
                'Dipolog City', // Capital
                'Godod',
                'Gutalac',
                'Jose Dalman',
                'Kalawit',
                'Katipunan',
                'La Libertad',
                'Labason',
                'Liloy',
                'Manukan',
                'Mutia',
                'Piñan',
                'Polanco',
                'President Manuel A. Roxas',
                'Rizal',
                'Salug',
                'Sergio Osmeña Sr.',
                'Siayan',
                'Sibuco',
                'Sibutad',
                'Sindangan',
                'Siocon',
                'Sirawai',
                'Tampilisan', // Total: 25 municipalities, 2 cities
            ],
            'Zamboanga del Sur' => [
                'Aurora',
                'Bayog',
                'Dimataling',
                'Dinas',
                'Dumalinao',
                'Dumingag',
                'Guipos',
                'Josefina',
                'Kumalarang',
                'Labangan',
                'Lakewood',
                'Lapuyan',
                'Mahayag',
                'Margosatubig',
                'Midsalip',
                'Molave',
                'Pagadian City', // Capital
                'Pitogo',
                'Ramon Magsaysay',
                'San Miguel',
                'San Pablo',
                'Sominot',
                'Tabina',
                'Tambulig',
                'Tigbao',
                'Tukuran',
                'Vincenzo A. Sagun',
                'Zamboanga City', // HUC
            ],
            'Zamboanga Sibugay' => [
                'Alicia',
                'Buug',
                'Diplahan',
                'Imelda',
                'Ipil', // Capital
                'Kabasalan',
                'Mabuhay',
                'Malangas',
                'Naga',
                'Olutanga',
                'Payao',
                'Roseller Lim',
                'Siay',
                'Talusan',
                'Titay',
                'Tungawan', // Total: 16 municipalities
            ],
            // NCR treated as a pseudo-province for its 16 cities and 1 municipality
            // 'NCR' => [
            //     'Caloocan City', // HUC
            //     'Las Piñas City', // HUC
            //     'Makati City', // HUC
            //     'Malabon City', // HUC
            //     'Mandaluyong City', // HUC
            //     'Manila', // HUC
            //     'Marikina City', // HUC
            //     'Muntinlupa City', // HUC
            //     'Navotas City', // HUC
            //     'Parañaque City', // HUC
            //     'Pasay City', // HUC
            //     'Pasig City', // HUC
            //     'Pateros', // Municipality
            //     'Quezon City', // HUC
            //     'San Juan City', // HUC
            //     'Taguig City', // HUC
            //     'Valenzuela City', // HUC
            //     // Total: 16 cities, 1 municipality
            // ],
        ];

        // Insert municipalities into the database
        foreach ($municipalitiesByProvince as $provinceName => $municipalities) {
            // Skip provinces with no municipalities
            if (empty($municipalities)) {
                continue;
            }

            // Special handling for NCR (no province)
            $province = $provinceName === 'NCR'
                ? null
                : DB::table('provinces')->where('name', $provinceName)->first();

            if ($provinceName !== 'NCR' && !$province) {
                throw new \Exception("Province '$provinceName' not found in the provinces table.");
            }

            foreach ($municipalities as $municipalityName) {
                DB::table('municipalities')->updateOrInsert(
                    [
                        'name' => $municipalityName,
                        'province_id' => $province ? $province->id : null,
                    ],
                    [
                        'name' => $municipalityName,
                        'province_id' => $province ? $province->id : null,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ]
                );
            }
        }
    }
}